export const ImagesMenu = [
  {
    "imgsrc":"/images/menu/1.jpg",
    "key":"men1"
  },
  {
    "imgsrc":"/images/menu/2.jpg",
    "key":"men2"
  },
  {
    "imgsrc":"/images/menu/3.jpg",
    "key":"men3"
  },
  {
    "imgsrc":"/images/menu/4.jpg",
    "key":"men4"
  },
  {
    "imgsrc":"/images/menu/5.jpg",
    "key":"men5"
  },
  {
    "imgsrc":"/images/menu/6.jpg",
    "key":"men6"
  },
  {
    "imgsrc":"/images/menu/7.jpg",
    "key":"men7"
  },
  {
    "imgsrc":"/images/menu/8.jpg",
    "key":"men8"
  },
  {
    "imgsrc":"/images/menu/9.jpg",
    "key":"men9"
  },
]
